In [152]:
import tweepy
import pandas as pd
from datetime import date

In [53]:
consumer_key = "add your consumer_key"
consumer_secret = "add your consumer_secret"
access_token = "add your access_token"
access_token_secret = "add your access_token_secret"

In [54]:
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

In [64]:
userID = "BarackObama"

tweets = api.user_timeline(screen_name=userID,
                           count=200,
                           include_rts = True,
                           #Do not include retweets
                           # Necessary to keep full_text 
                           # otherwise only the first 140 words are extracted
                           tweet_mode = 'extended'
                           )

In [187]:
tweetss = []
likes = []
timee = []
retweets = []

for info in tweets[:200]:
     
     print("ID: {}".format(info.id))
     retweets.append(info.retweet_count)
     #time_stamp = info.created_at
     timee.append(info.created_at)
     likes.append(info.favorite_count)
     tweetss.append(info.full_text)
     print("\n")
#print(len(tweetss))
#print(len(likes))
#print(len(timee))
#print(timee)

ID: 1496947181214916614


ID: 1496617242406096898


ID: 1496241395174150144


ID: 1496241393018327044


ID: 1496241389104939008


ID: 1496241385120407553


ID: 1496241382146646028


ID: 1495775428421824512


ID: 1494394668506824712


ID: 1494394666606903300


ID: 1494394664358752260


ID: 1494394661326176264


ID: 1493653951752900611


ID: 1493284067898544131


ID: 1491925070163365896


ID: 1491774011000475648


ID: 1491774008693608460


ID: 1491774004411129863


ID: 1489298145955700741


ID: 1489298144626151432


ID: 1488905269434363908


ID: 1488165435744960514


ID: 1487470802824011780


ID: 1487470798185152518


ID: 1487176180524531722


ID: 1487131150321598469


ID: 1486730904970006542


ID: 1486452033926406151


ID: 1484280257800773636


ID: 1484280256404103169


ID: 1484280253098995712


ID: 1484280251257696265


ID: 1484280247650557956


ID: 1484222198600634380


ID: 1483862020739014656


ID: 1483560345218207754


ID: 1483122103708798978


ID: 1483080590631096322


ID: 1482042628393041921


ID: 1482042626299805700


ID: 1481710791481077764


ID: 1481417826753728518


ID: 1481417823104688131


ID: 1481417820692955136


ID: 1480592016685903888


ID: 1480591880215793675


ID: 1479945848071106570


ID: 1479512077878366209


ID: 1479090410211393543


ID: 1477301228405198854


ID: 1476946708022112259


ID: 1476009363689123849


ID: 1475527416231739393


ID: 1475101314149494788


ID: 1475101312127840264


ID: 1474749380678803459


ID: 1473745362112372744


ID: 1473012930241302539


ID: 1472258324695552005


ID: 1471906370454753288


ID: 1471865356557893639


ID: 1471549865247260677


ID: 1471168498768519169


ID: 1471168495312420877


ID: 1471148313835618309


ID: 1470868859704029189


ID: 1470868857221009414


ID: 1470770564860162055


ID: 1469020221931409411


ID: 1468955080082690056


ID: 1468249298710286342


ID: 1467576072401309708


ID: 1467245114338811905


ID: 1466852810260164610


ID: 1466808436939759616


ID: 1466527628878389257


ID: 1466150329309880325


ID: 1465817526315716609


ID: 1465689642146185219


ID: 1465010274029785092


ID: 1464644791816400899


ID: 1463881629861097483


ID: 1462118955930247174


ID: 1461379395512381445


ID: 1461016629119225867


ID: 1460676660769001475


ID: 1460650387107688450


ID: 1459940709088350208


ID: 1458800452393439239


ID: 1458800450283659272


ID: 1458601125960163332


ID: 1458519999308500997


ID: 1458457339535761414


ID: 1458212068646133771


ID: 1458212067899584515


ID: 1458212066179887107


ID: 1458212064904744961


ID: 1457713555361476611


ID: 1456350991419326466


ID: 1455535546395156483


ID: 1455535543207530496


ID: 1454115859534950406


ID: 1453757017148043272


ID: 1453413921822580747


ID: 1452687910055002115


ID: 1452435380238622721


ID: 1452052888268808195


ID: 1451896893743767555


ID: 1451260787373350914


ID: 1450861885889388546


ID: 1450854359630295040


ID: 1450148473295228929


ID: 1449869175711838213


ID: 1448371831698767877


ID: 1447000963672428545


ID: 1446868274671755271


ID: 1446211368554795010


ID: 1446211362103889924


ID: 1445464097752035330


ID: 1445464092555112448


ID: 1445464090432868355


ID: 1445464088335708160


ID: 1445434311692505089


ID: 1444739482050301953


ID: 1444045206916063234


ID: 1442983205502586882


ID: 1442918092892299264


ID: 1442912660522106882


ID: 1442647737087012868


ID: 1441417526890536967


ID: 1441107723941081088


ID: 1440069585865039874


ID: 1440069580437671952


ID: 1438541175607242766


ID: 1437878127011696641


ID: 1437808539016343558


ID: 1436655211846721537


ID: 1436111878045028353


ID: 1435736097535954944


ID: 1435657058536337418


ID: 1435262267013181440


ID: 1434894261112164352


ID: 1434894258780114956


ID: 1432822074117079040


ID: 1431244052742213641


ID: 1431244029749047296


ID: 1431244020978753546


ID: 1431244018248257537


ID: 1430565712330952705


ID: 1430187128017805316


ID: 1427639234576490506


ID: 1426589810131718148


ID: 1425812142176018436


ID: 1423690346416967685


ID: 1423690344798035972


ID: 1423361943100854272


ID: 1420135139347034112


ID: 1419758772445057031


ID: 1419451561051189248


ID: 1418715270961500163


ID: 1418244880246075392


ID: 1416802924424957955


ID: 1416480269800939521


ID: 1416480267024306184


ID: 1416414493756727300


ID: 1415692657003667457


ID: 1413848757083545601


ID: 1413576041482932225


ID: 1413494731997392899


ID: 1413287052666363909


ID: 1412864203258540033


ID: 1412075067903811588


ID: 1412075066070810625


ID: 1411671471366234114


ID: 1409935053711458304


ID: 1408833192543637506


ID: 1408818108224131074


ID: 1408485199189512196


ID: 1407700032061689856


ID: 1407444434157977601


ID: 1406628503488024581


ID: 1406265927444963349


ID: 1405874188406210560


ID: 1405578420155731976


ID: 1405578419237163008


ID: 1405578417865691139


ID: 1405578416095731712


ID: 1404885369146036230


ID: 1403018040934027266


ID: 1401226146973470722


ID: 1400845069217828872


ID: 1400484971760996354


ID: 1400172449816317953

In [186]:
retweet_count = info.retweet_count 
retweet_count

1695

In [169]:
#print(timee)
a = timee[0]
print(a)
#print(datetime.date(a))
#print(datetime.datetime.date(a))

2022-02-24 20:36:34+00:00

In [188]:
df = pd.DataFrame({'Tweet':tweetss,'Likes':likes,'Date':timee,'Retweets':retweets})

In [189]:
df

,Tweet,Likes,Date,Retweets
0,"Last night, Russia launched a brazen attack on...",137358,2022-02-24 20:36:34+00:00,23623
1,Michelle and I were sad to hear about the pass...,9195,2022-02-23 22:45:31+00:00,1042
2,I want to thank everyone who has joined @AllOn...,3506,2022-02-22 21:52:02+00:00,499
3,"And in Ohio, @AllOnTheLine held 139 training s...",3319,2022-02-22 21:52:01+00:00,441
4,"In North Carolina, Karla Icaza De Austin, an A...",1642,2022-02-22 21:52:00+00:00,246
...,...,...,...,...
188,"Happy birthday, Sasha! You’ve grown so much, a...",281826,2021-06-10 15:55:42+00:00,9762
189,"It's always great catching up with @POTUS, and...",83816,2021-06-05 17:15:21+00:00,9402
190,"On National Gun Violence Awareness Day, we #we...",32207,2021-06-04 16:01:05+00:00,4390
191,Coaches like Ernest Radcliffe are changing liv...,17434,2021-06-03 16:10:11+00:00,1894
192,"Yesterday, I sat down with some of the Obama P...",22801,2021-06-02 19:28:20+00:00,1695

In [190]:
df.to_csv('file1.csv')